### ISSUE TITLE
Actualizar Correction Step

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/correction_step#17]
```[tasklist]
### Tasks

- [x] Estructura básica del step
- [x] Corregir magnitud de la alerta y de las prv_detections
- [x] Producir mensajes de scribe en tópico w_detection con instrucción update y upsert=true
- [x] Producir mensajes con las detecciones que recibe desde prv_candidates_step en tópico partial-lightcurve
```

# Criterio de aceptación
- Se generan mensajes en tópicos de w_detection y partial-lightcurve
- Funciona para ATLAS y ZTF
- Corrección está correcta según los casos de prueba
- Se generan métricas de prometheus en endpoint host:8000/metrics
- Consume más de un mensaje a la vez

# Criterio de aceptación no funcional
- Deployment usa métricas de `consumed_messages` para HPA
